menu:
  Home:
  Archives: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: dermothaughey
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-89814809-1

# Facebook comment
disqus_shortname: blog-dermothaughey-com
